name: Record Test Time
on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  record_test_time:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
      - name: Setup cache key and directory for gems cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle install
        env:
          RAILS_ENV: test
        run: |
          gem install bundler:1.16.6
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          bundle exec rake db:drop
          bundle exec rake db:create
          bundle exec rake db:schema:load
          bundle exec rake db:test:prepare
          bundle exec rspec spec --format progress
      - uses: actions/upload-artifact@v1
        with:
          name: my_spec_log
          path: ./my_spec_log.csv
      - uses: actions/download-artifact@v2
        with:
          name: my_spec_log

      - name: Create commits
        run: |
          git config user.name 'Oluwakunle Fakorede'
          git config user.email 'fakoredeoluwakunle2626@gmail.com'
          git add my_spec_log.csv
          git commit -m "Modify tracked file during workflow"
          git reset --hard

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
#          commit-message: Update report
#          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: real-patches-update-work
          base: setup-gh-actions
          delete-branch: true
          title: '[Real] Update reports'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          reviewers: frostyblok
          draft: false

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
      - name: Display structure of downloaded files
        run: ls -R

#  download:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/download-artifact@v2
#        with:
#          name: my_spec_log
#      - name: Create commits
#        run: |
#          git config user.name 'Oluwakunle Fakorede'
#          git config user.email 'fakoredeoluwakunle2626@gmail.com'
#          git add my_spec_log.csv
#          git commit -m "Modify tracked file during workflow"
#
#      - name: Create Pull Request
#        id: cpr
#        uses: peter-evans/create-pull-request@v3
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
##          commit-message: Update report
##          committer: GitHub <noreply@github.com>
#          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
#          signoff: false
#          branch: real-patches-update
#          base: setup-gh-actions
#          delete-branch: true
#          title: '[Real] Update reports'
#          body: |
#            Update report
#            - Updated with *today's* date
#            - Auto-generated by [create-pull-request][1]
#
#            [1]: https://github.com/peter-evans/create-pull-request
#          labels: |
#            report
#            automated pr
#          reviewers: frostyblok
#          draft: false
#
#      - name: Check outputs
#        run: |
#          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
#          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
#      - name: Display structure of downloaded files
#        run: ls -R
